<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>C2</name>
   <tag></tag>
   <elementGuidId>a17b65a6-1eac-4492-9317-4d0f6fcb03d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@data-id=&quot;VAC-SOUTH3&quot;])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.no-outline.refinementInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ad81b4f-f440-4289-8949-775b220161cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-outline refinementInput</value>
      <webElementGuid>c7a1b2d1-1160-4c3a-8c8f-9d25cd82c7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d1669f83-e904-463a-80ad-7170587d7027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>VAC-Unallocated</value>
      <webElementGuid>e3845edf-628b-41cc-96c3-d7c3f68002a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-quota-refinement[1]/div[@class=&quot;main-container&quot;]/div[3]/div[@class=&quot;tab-List tab-Refinement&quot;]/div[2]/c-qr-refinement-panel[1]/div[@class=&quot;slds-grid page-height&quot;]/div[@class=&quot;slds-col slds-size_6-of-6&quot;]/div[@class=&quot;table-container&quot;]/table[@class=&quot;slds-no-row-hover slds-table slds-table_cell-buffer slds-table_bordered slds-table_col-bordered refinement-table&quot;]/tbody[1]/tr[@class=&quot;slds-hint-parent childrenRows&quot;]/td[4]/input[@class=&quot;no-outline refinementInput&quot;]</value>
      <webElementGuid>b50af5c3-f565-4880-9157-5d83f1af4108</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[17]</value>
      <webElementGuid>b95a5494-7dda-4ec9-a672-c8e094345f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/siqic-quota-refinement/div/div[3]/div[2]/div[2]/c-qr-refinement-panel/div/div/div[3]/table/tbody/tr[2]/td[4]/input</value>
      <webElementGuid>d649386b-907d-4771-87f0-a123c6013df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/input</value>
      <webElementGuid>2bd7a462-f4f2-44f4-bd7e-3f8ededeee87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>ca487181-8104-4406-9021-feb7511e3aa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
