<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VAC-Unallocated_no-outline refinementInput - Copy (9)</name>
   <tag></tag>
   <elementGuidId>c4aedada-96e7-487f-9290-d354f4f4cdf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@data-id=&quot;VAC-Unallocated&quot;])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.no-outline.refinementInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4cf90685-2f11-48fe-8058-0dcde50a1139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-outline refinementInput</value>
      <webElementGuid>227ae21f-f445-4094-9a11-098cffdff0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5a558ab6-b0e7-447c-8329-428119925f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>VAC-Unallocated</value>
      <webElementGuid>c5747ef3-7e5f-4ac8-a025-e6c8a13e58ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-quota-refinement[1]/div[@class=&quot;main-container&quot;]/div[3]/div[@class=&quot;tab-List tab-Refinement&quot;]/div[2]/c-qr-refinement-panel[1]/div[@class=&quot;slds-grid page-height&quot;]/div[@class=&quot;slds-col slds-size_6-of-6&quot;]/div[@class=&quot;table-container&quot;]/table[@class=&quot;slds-no-row-hover slds-table slds-table_cell-buffer slds-table_bordered slds-table_col-bordered refinement-table&quot;]/tbody[1]/tr[@class=&quot;slds-hint-parent childrenRows&quot;]/td[4]/input[@class=&quot;no-outline refinementInput&quot;]</value>
      <webElementGuid>dc845e14-975b-4706-aa45-2065607c87fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[17]</value>
      <webElementGuid>8ea9b27c-51f6-4d9f-9179-108796d8ddb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/siqic-quota-refinement/div/div[3]/div[2]/div[2]/c-qr-refinement-panel/div/div/div[3]/table/tbody/tr[2]/td[4]/input</value>
      <webElementGuid>a3fd7cf6-92d9-49cd-9dd5-4554a2ccd9e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/input</value>
      <webElementGuid>4aad21d4-19f6-4a79-b824-5d732d73f45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>99600646-d378-40ca-907c-6b285860cfa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
