<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_radio</name>
   <tag></tag>
   <elementGuidId>be8432b9-7666-48b1-9ccf-249b1d8613ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[div[text()='vinod Bendre']]/preceding-sibling::td/input[@name='radio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;radio&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddb745e4-cb5c-4aa9-887f-053aa6179d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>eaa6cc2c-1f77-4875-baff-613719a83e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>fc4983aa-2f2f-43e1-93e8-5f36ecc27fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>a4I5e0000004pSkEAI</value>
      <webElementGuid>310f2c3a-f9bb-4873-b723-72d9f7715b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-quota-refinement[1]/div[@class=&quot;main-container&quot;]/div[3]/div[@class=&quot;tab-List tab-Approvals&quot;]/c-qr-approvals-tab[1]/div[@class=&quot;approval-container&quot;]/div[@class=&quot;approval-table-container&quot;]/div[@class=&quot;table-scroll&quot;]/table[@class=&quot;slds-table slds-table_cell-buffer slds-table_bordered slds-table_col-bordered&quot;]/tbody[1]/tr[@class=&quot;slds-hint-parent&quot;]/td[1]/input[1]</value>
      <webElementGuid>5b007181-9f45-405a-b405-2412d448ceb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='radio']</value>
      <webElementGuid>76bd9a20-bd17-4d8f-8fb8-dd326fd0140b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[4]/siqic-quota-refinement/div/div[3]/div[3]/c-qr-approvals-tab/div/div/div/table/tbody/tr/td/input</value>
      <webElementGuid>efa862f0-36e0-4c9a-8a33-8abc2a6e804e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//c-qr-approvals-tab/div/div/div/table/tbody/tr/td/input</value>
      <webElementGuid>24cc49ac-df6f-4aa5-943e-abcf070695d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'radio']</value>
      <webElementGuid>6284de7c-c5e9-4965-b174-733b2398035e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
