<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>R2</name>
   <tag></tag>
   <elementGuidId>1c4aa7f7-f0b7-4723-8f41-17dd86800bfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@data-id=&quot;VAC-SOUTH3&quot;])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.no-outline.refinementInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c8d121e-9252-4de1-adf1-048b9b1918e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-outline refinementInput</value>
      <webElementGuid>a767aa5c-ce40-4e6d-bc87-11d623f140ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a708e7f0-da21-4d88-b235-dc9f3c7eee3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>VAC-Unallocated</value>
      <webElementGuid>a7b721cf-6f7b-4ef2-9ac2-133f44fce1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-quota-refinement[1]/div[@class=&quot;main-container&quot;]/div[3]/div[@class=&quot;tab-List tab-Refinement&quot;]/div[2]/c-qr-refinement-panel[1]/div[@class=&quot;slds-grid page-height&quot;]/div[@class=&quot;slds-col slds-size_6-of-6&quot;]/div[@class=&quot;table-container&quot;]/table[@class=&quot;slds-no-row-hover slds-table slds-table_cell-buffer slds-table_bordered slds-table_col-bordered refinement-table&quot;]/tbody[1]/tr[@class=&quot;slds-hint-parent childrenRows&quot;]/td[4]/input[@class=&quot;no-outline refinementInput&quot;]</value>
      <webElementGuid>aee3c738-f10a-4aff-a0ff-754ccbec135a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[17]</value>
      <webElementGuid>aa46044e-210f-49d4-8910-d9855b58edb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/siqic-quota-refinement/div/div[3]/div[2]/div[2]/c-qr-refinement-panel/div/div/div[3]/table/tbody/tr[2]/td[4]/input</value>
      <webElementGuid>36d21a4e-e6ff-45ba-86eb-a4d7421b6c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/input</value>
      <webElementGuid>a095b5ec-39fd-4398-8c90-e7dde8ab2fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>be07a4ec-809a-4ecd-852f-fcbf497fa7ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
