<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>R4</name>
   <tag></tag>
   <elementGuidId>0db4978e-7a85-40f5-b907-2e6d4e4dde07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@data-id=&quot;VAC-SOUTH1&quot;])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.no-outline.refinementInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7eb9bfee-8d72-41f3-b751-9e958d9a8551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-outline refinementInput</value>
      <webElementGuid>cfc95bb9-e649-4086-9f4c-48647c5dd746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dbabb2e6-bb28-46d8-95fb-4a63e436b13f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>VAC-Unallocated</value>
      <webElementGuid>cc77f394-5cf2-4ff6-9f91-196788c3a992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-quota-refinement[1]/div[@class=&quot;main-container&quot;]/div[3]/div[@class=&quot;tab-List tab-Refinement&quot;]/div[2]/c-qr-refinement-panel[1]/div[@class=&quot;slds-grid page-height&quot;]/div[@class=&quot;slds-col slds-size_6-of-6&quot;]/div[@class=&quot;table-container&quot;]/table[@class=&quot;slds-no-row-hover slds-table slds-table_cell-buffer slds-table_bordered slds-table_col-bordered refinement-table&quot;]/tbody[1]/tr[@class=&quot;slds-hint-parent childrenRows&quot;]/td[4]/input[@class=&quot;no-outline refinementInput&quot;]</value>
      <webElementGuid>3fa92ffa-d304-434b-804c-46998e03fc65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[17]</value>
      <webElementGuid>ec224866-602f-4473-8ad1-26bd63d0ecba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/siqic-quota-refinement/div/div[3]/div[2]/div[2]/c-qr-refinement-panel/div/div/div[3]/table/tbody/tr[2]/td[4]/input</value>
      <webElementGuid>89ce9428-e59f-4925-92e5-f51927952ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/input</value>
      <webElementGuid>1fe089c2-12ed-4929-b2e6-5ce59f346e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>fbdadfe3-afff-400d-8b26-45a47c283633</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
