<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>R5</name>
   <tag></tag>
   <elementGuidId>2226cd2c-ec4d-478d-8b42-f16b43245bd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@data-id=&quot;VAC-SOUTH2&quot;])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.no-outline.refinementInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6b32fa4-662b-4487-b7cb-d5ed00ddbc0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-outline refinementInput</value>
      <webElementGuid>8dede3f5-2b01-44ff-b06e-c1ab403e3323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>632f602f-30b6-42b1-a551-4ff5b6c3309f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>VAC-Unallocated</value>
      <webElementGuid>972a0fe4-9791-462d-a1f8-c667ce18692b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-quota-refinement[1]/div[@class=&quot;main-container&quot;]/div[3]/div[@class=&quot;tab-List tab-Refinement&quot;]/div[2]/c-qr-refinement-panel[1]/div[@class=&quot;slds-grid page-height&quot;]/div[@class=&quot;slds-col slds-size_6-of-6&quot;]/div[@class=&quot;table-container&quot;]/table[@class=&quot;slds-no-row-hover slds-table slds-table_cell-buffer slds-table_bordered slds-table_col-bordered refinement-table&quot;]/tbody[1]/tr[@class=&quot;slds-hint-parent childrenRows&quot;]/td[4]/input[@class=&quot;no-outline refinementInput&quot;]</value>
      <webElementGuid>f4d6c67e-389e-46ed-9566-d016a0faa78f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[17]</value>
      <webElementGuid>6022101a-ab49-4579-a0e0-105f0822c0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/siqic-quota-refinement/div/div[3]/div[2]/div[2]/c-qr-refinement-panel/div/div/div[3]/table/tbody/tr[2]/td[4]/input</value>
      <webElementGuid>db7c1149-2725-4ea5-94b7-ab794acc0717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/input</value>
      <webElementGuid>d17ce78d-9199-4479-8231-65e3bde91c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>a8f74a44-7bf3-40cd-abd6-7e0fbcb738cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
