<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Approvals1</name>
   <tag></tag>
   <elementGuidId>4f557e9a-28f0-46f2-8dae-e190d99d5ea8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Approvals']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e17c5a92-883e-4aa3-9716-16047d176efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabs</value>
      <webElementGuid>e66a4254-c2e4-4f3a-942f-dc9cdab6f3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Approvals</value>
      <webElementGuid>fcba7bb7-e542-43cd-a9b5-a181da814db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approvals1</value>
      <webElementGuid>d5994bb9-7b67-49ea-8834-b5f0c77f9d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-quota-refinement[1]/div[@class=&quot;main-container&quot;]/div[@class=&quot;main-screen&quot;]/div[@class=&quot;slds-grid tabHeader-container&quot;]/div[@class=&quot;slds-col slds-size_1-of-2&quot;]/a[@class=&quot;tab-link&quot;]/span[@class=&quot;tabs&quot;]</value>
      <webElementGuid>490375c8-2e7e-4aac-a59c-213669ce579b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[4]/siqic-quota-refinement/div/div[2]/div/div/a[3]/span</value>
      <webElementGuid>3e03d697-03d3-4d96-a404-8e4207bcff2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refinement'])[3]/following::span[1]</value>
      <webElementGuid>101c7888-6706-4afc-8ea1-e33a984c3dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[2]/following::span[2]</value>
      <webElementGuid>48bb79f9-1a1d-4ffd-8358-6295d8f4ca4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[4]/preceding::span[2]</value>
      <webElementGuid>6336390f-a095-43ec-8e70-f393ac0148f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Unit'])[4]/preceding::span[2]</value>
      <webElementGuid>6d820276-7c2f-4d51-8144-ea89157873db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Approvals']/parent::*</value>
      <webElementGuid>9806f199-5dde-483f-bf92-0bbb43aed88d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/span</value>
      <webElementGuid>e4296088-8683-430d-a5c2-3dec05ed3dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Approvals1' or . = 'Approvals1')]</value>
      <webElementGuid>326ab40a-9fe1-4d92-9e09-10ce271a6206</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
