<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Status_slds-icon slds-icon_x-small slds_cb963e</name>
   <tag></tag>
   <elementGuidId>700895dc-fe3d-45f9-90dc-823c446367e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//lightning-menu-item/a/span/lightning-primitive-icon)[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>9e7bfbfa-96dd-4c9d-861b-3ecee94a7b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-icon slds-icon_x-small slds-icon-text-default slds-m-right_x-small</value>
      <webElementGuid>92c35cda-eace-4ef2-9557-40f45d88c539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>13a5e4b2-c363-4ddf-a3d3-09219affa107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>custom_apps</value>
      <webElementGuid>efe13807-a051-4217-a0c9-c20a64c65192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c04e0082-d04e-441d-a11c-d2f2256625bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 52 52</value>
      <webElementGuid>f835d23f-318c-4999-8dd3-0972fb16fb55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>7843f693-b37e-41cd-a43a-1fec35a94065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-qr_-list-page-lwc[1]/div[@class=&quot;row&quot;]/div[@class=&quot;slds-grid slds-p-around--medium&quot;]/div[@class=&quot;slds-col slds-border_left&quot;]/section[@class=&quot;slds-modal slds-fade-in-open slds-modal_small&quot;]/div[@class=&quot;slds-modal__container&quot;]/div[1]/table[@class=&quot;list table-example slds-is-relative slds-scrollable&quot;]/tbody[1]/tr[@class=&quot;slds-hint-parent dataRow&quot;]/td[1]/div[@class=&quot;slds-grid&quot;]/lightning-menu-item[@class=&quot;slds-col slds-dropdown__item&quot;]/a[1]/span[@class=&quot;slds-truncate&quot;]/lightning-primitive-icon[1]/svg[@class=&quot;slds-icon slds-icon_x-small slds-icon-text-default slds-m-right_x-small&quot;]</value>
      <webElementGuid>f7fda3c1-d159-47d7-8341-7c057a33336c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::*[name()='svg'][2]</value>
      <webElementGuid>ce5e93b3-6dc8-4a31-8149-258a574867dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Position Name'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>0df11afc-a4c5-4fea-8dea-95209b7e42d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VAC-REGION'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>e97fbd2a-a1db-429d-9ce2-6eb7461cfd2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nguyen Thanh Luan'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>228bc3f2-36d5-44bd-b0db-42fbea23bd10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
