<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Comment_comment-textarea</name>
   <tag></tag>
   <elementGuidId>0e965b9b-8ffd-4cca-a6a2-71ac0ea09720</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//textarea)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.windowViewMode-normal.oneContent.active.lafPageHost > siqic-quota-refinement > div.main-container > div:nth-of-type(3) > div.tab-List.tab-Approvals > c-qr-approvals-tab > div.approval-container > div.approval-footer > div.slds-grid > div.slds-col.slds-size_2-of-3 > div.slds-grid > div.slds-col.slds-size_2-of-3.form-actions > textarea.comment-textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5daeb804-789e-47a6-99a8-8c587d8e5655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f0259d1a-9797-4a04-8ea7-707dfd6ec194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comment-textarea</value>
      <webElementGuid>ea0eb269-2000-44f9-b44c-be2806a971fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1358da6e-5af7-4bc7-914a-8f9940edfa73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-quota-refinement[1]/div[@class=&quot;main-container&quot;]/div[3]/div[@class=&quot;tab-List tab-Approvals&quot;]/c-qr-approvals-tab[1]/div[@class=&quot;approval-container&quot;]/div[@class=&quot;approval-footer&quot;]/div[@class=&quot;slds-grid&quot;]/div[@class=&quot;slds-col slds-size_2-of-3&quot;]/div[@class=&quot;slds-grid&quot;]/div[@class=&quot;slds-col slds-size_2-of-3 form-actions&quot;]/textarea[@class=&quot;comment-textarea&quot;]</value>
      <webElementGuid>5c19cd7e-9058-4994-a7da-aa036dfd9542</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[4]/siqic-quota-refinement/div/div[3]/div[3]/c-qr-approvals-tab/div/div[2]/div/div/div/div[2]/textarea</value>
      <webElementGuid>70f328fb-b2a0-4c65-9b9d-e3fa99673fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/siqic-quota-refinement/div/div[3]/div[3]/c-qr-approvals-tab/div/div[2]/div/div/div/div[2]/textarea</value>
      <webElementGuid>cc6b97db-f069-48e0-8a85-67084df581f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
