<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Business Unit_slds-radio_faux</name>
   <tag></tag>
   <elementGuidId>08567d5d-7ac4-4f1e-a8c0-acafc34c62d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-content-id-1-1599']/div[2]/table/tbody/tr[4]/td/span/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6d86a997-17ae-4047-8fde-420923556031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-radio_faux</value>
      <webElementGuid>c838d51d-c169-4dc1-be34-3bc20ea36d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-content-id-1-1599&quot;)/div[@class=&quot;delegation-table&quot;]/table[@class=&quot;slds-table slds-table_cell-buffer slds-table_bordered slds-table_col-bordered table-side-borders&quot;]/tbody[1]/tr[@class=&quot;slds-hint-parent&quot;]/td[1]/span[@class=&quot;slds-radio&quot;]/label[@class=&quot;slds-radio__label&quot;]/span[@class=&quot;slds-radio_faux&quot;]</value>
      <webElementGuid>04a0c7d2-e63b-43ec-9f5d-2aa8e8e06755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>indicator</value>
      <webElementGuid>8bf8c071-776e-4d64-b545-509f4e9a9cc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-content-id-1-1599']/div[2]/table/tbody/tr[4]/td/span/label/span</value>
      <webElementGuid>5ea1a194-ad0e-432e-8639-6cf86140f1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/span/label/span</value>
      <webElementGuid>89118c29-4850-40d8-a0f5-d63592c29dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-input[@id='VAC-SOUTH1-1618']/div/span/label/span</value>
      <webElementGuid>e6125202-2d18-4ab9-9318-585c1be2a42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/lightning-input/div/span/label/span</value>
      <webElementGuid>aef784da-2d62-4b92-b5ed-f0a1566eedee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-content-id-1-3396']/div[2]/table/tbody/tr/td/span/label/span</value>
      <webElementGuid>633be984-1f2d-4c91-94c6-36aad21d7223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>1dd9e7ae-7ceb-4cda-8ad0-b5f5fc2e94b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
