<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Delegation</name>
   <tag></tag>
   <elementGuidId>1b86e995-f9ec-4445-b981-1550a61fa5b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal-heading-01-3396</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[text()='Delegation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>79f3a8b4-3495-4b61-8485-eef8e2b5a1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-modal__title slds-hyphenate</value>
      <webElementGuid>618e25f1-49f9-4d90-a6c1-089b79f86faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-heading-01-3396</value>
      <webElementGuid>56178f5a-d93f-4b01-9f32-f30bd827f166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delegation</value>
      <webElementGuid>d9f813d9-7cfe-4fe8-a709-1074e7be560e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-heading-01-3396&quot;)</value>
      <webElementGuid>38d814c6-ab43-454d-b1ad-7eaaf820e4c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='modal-heading-01-3396']</value>
      <webElementGuid>0471d117-1d94-452f-94d0-5448897e90f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[3]/siqic-qr_-list-page-lwc/div/div/div[3]/c-qr-delegate-lwc/div/section/div/div/h1</value>
      <webElementGuid>00a48874-36e9-4267-8dee-6df45ccd19d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel and close'])[1]/following::h1[1]</value>
      <webElementGuid>ae39166f-0de5-48e1-afd8-fe988f7ca3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Action'])[560]/following::h1[1]</value>
      <webElementGuid>da3c0f61-c794-4bc9-ab9d-e9f463c65991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Type'])[1]/preceding::h1[1]</value>
      <webElementGuid>b1c1d982-5f2d-4136-b51c-3ffb60d05852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HO'])[1]/preceding::h1[1]</value>
      <webElementGuid>4a7e5fa3-866c-437d-a3df-ddc896adde4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delegation']/parent::*</value>
      <webElementGuid>0a9b4388-3579-4f72-afeb-33643c1fa064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>66ccfa6d-d478-49ef-988f-f5cb719b3d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'modal-heading-01-3396' and (text() = 'Delegation' or . = 'Delegation')]</value>
      <webElementGuid>72456bdf-8ece-4f35-bbe2-6a12cbe9694a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
